### ISSUE TITLE
Publish latest code changes to npm

### ISSUE THREAD

**Issue by harishanchu** [felixge/node-stack-trace#16]
Hey, could you please publish latest code changes to npm.

Thanks

**Comment by lloiser** [comment]
+1

**Comment by lloiser** [comment]
@felixge please!

**Comment by gajus** [comment]
@felixge can you add me as a contributor to this repository and the NPM package?

**Comment by felixge** [comment]
@gajus sure, what's your npm user name?

**Comment by gajus** [comment]
"gajus"

**Comment by felixge** [comment]
@gajus added on npm/gh.

**Comment by gajus** [comment]
I am working on https://github.com/gajus/isomorphic-webpack. I have had a few issues related with this project. I will pick those up as I get back to the relevant issues.

**Comment by felixge** [comment]
@gajus sure, sgtm
