### ISSUE TITLE
Support for all browsers

### ISSUE THREAD

**Issue by nickasd** [felixge/node-stack-trace#19]
Hi, this module seems very interesting but unfortunately I'm not able to make it work with Firefox (Chrome works). Are there any plans to integrate other browsers like stack-trace.js? That would be awesome!

**Comment by niemyjski** [comment]
I'd recommend using stacktrace.js for front end and this library for node apps (It's what we do in the exceptionless js client I work on in my free time). It's also what the stacktrace.js library recommends. We could probably support this some day but only if others are chipping in to submit a pr and help maintain it long term.
