### ISSUE TITLE
Project/Maintainer status

### ISSUE THREAD

**Issue by niemyjski** [felixge/node-stack-trace#34]
@felixge would you mind appointing a second maintainer to help respond to issues and or pull requests. The project seems slightly abandoned and is still super useful and the recommended way to shred node stack traces.

**Comment by felixge** [comment]
@niemyjski hey, I'd be happy to add you to the project if you're interested. If so, please also let me know your npm username.

**Comment by niemyjski** [comment]
@felixge Thanks! My npm username is: niemyjski I'm also on discord as well.

**Comment by felixge** [comment]
@niemyjski added you on GH and NPM. Thanks for offering to help. Oh and please don't put bitcoin mining stuff into the package, it's bad for the environment 🙈.

**Comment by niemyjski** [comment]
Thanks, I will never do anything unethical like that.

**Comment by felixge** [comment]
> Thanks, I will never do anything unethical like that.

Good : ). I mean I don't think you would, but my liberal policy towards adding contributors hasn't always worked out for everybody, see https://gist.github.com/felixge/024827e7f09048d7bee2ad7c397e6ace 🙈
