### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module path/to/stack-trace/index.js from path/to/my/src/index.ts not supported.

### ISSUE THREAD

**Issue by talhabalaj** [felixge/node-stack-trace#37]
This error is appearing not matter what I do. I tried dynamic import as suggested by the error message but it didn't work. I have tried changing typescript configurations but nothing. Added `{ "type": "module" }` to my package.json but no result.

```no-lang
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/talha/projects/Vez-Logger/node_modules/stack-trace/index.js from /home/talha/projects/Vez-Logger/src/index.ts not supported.
Instead change the require of index.js in /home/talha/projects/Vez-Logger/src/index.ts to a dynamic import() which is available in all CommonJS modules.
    at /home/talha/projects/Vez-Logger/src/index.ts:60:79 {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
```

**Comment by Giddu** [comment]
@talhabalaj I faced the same issue while trying to use the library today. For me using the **0.0.10** version instead of the latest one worked.

**Comment by talhabalaj** [comment]
Yeah @Giddu I tried, the recent change is the issue

**Comment by yashspr** [comment]
@Giddu Thank you. v0.0.10 works!

**Comment by IJuanI** [comment]
I think this is due to having "type": "module" set in the packages.json in the newer version

**Comment by talhabalaj** [comment]
I moved my project to use ESM modules. 
Follow this: https://pawelgrzybek.com/all-you-need-to-know-to-move-from-commonjs-to-ecmascript-modules-esm-in-node-js/

**Comment by AlanGreyjoy** [comment]
If I could put everyone into one room that thinks esm belongs in the backend, I would set fire to the room....
