### ISSUE TITLE
does not work with node 18?

### ISSUE THREAD

**Issue by jric** [felixge/node-stack-trace#41]
jric@Alexs-MacBook-Pro-3 test % npm i stack-trace
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'stack-trace@1.0.0-pre1',
npm WARN EBADENGINE   required: { node: '16' },
npm WARN EBADENGINE   current: { node: 'v18.3.0', npm: '8.11.0' }
npm WARN EBADENGINE }

**Comment by jric** [comment]
Would you be able to merge https://github.com/felixge/node-stack-trace/pull/39 ?

**Comment by jric** [comment]
I verified that the tests pass with node v 18

**Comment by jric** [comment]
I have temporarily published the fixed version on npm as https://www.npmjs.com/package/stack-trace-anynode in case anyone else is in a hurry for this fix.

**Comment by niemyjski** [comment]
@felixge can you please merge #39

**Comment by niemyjski** [comment]
I've merged #39, I'll push a new version, it's been a while :)

**Comment by niemyjski** [comment]
@jric 1.0.0-pre2 has been pushed to npm.

**Comment by jric** [comment]
Thank you.

**Comment by niemyjski** [comment]
No problem, sorry for taking so long to get this merged.
